language: java

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - python3

env:
  - CXX="g++-4.8"

script: >
  cd cpp                 &&
  make                   &&
  cd ..                  &&

  cd python              &&
  python setup.py test   &&
  python3 setup.py test  &&
  cd ..                  &&

  cd scala               &&
  mvn test               &&
  cd ..
