language: java
# jdk: oraclejdk7

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - python3

cache:
  directories:
    - /var/lib/apt
    - /var/cache/apt

env:
  - CXX="g++-4.8"

script: ./test-all.sh
